// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzCvHOWM6YCw08_Em9JjLL4YF_4zoph9g',
    appId: '1:487531490423:web:3871209883ff35f039aa72',
    messagingSenderId: '487531490423',
    projectId: 'sadeem-c5307',
    authDomain: 'sadeem-c5307.firebaseapp.com',
    storageBucket: 'sadeem-c5307.firebasestorage.app',
    measurementId: 'G-NCGNC8MNXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD139l5Ryhj13Si_jN7lhLsgflO8zqNc_4',
    appId: '1:487531490423:android:8cb6e0d7bd41d53a39aa72',
    messagingSenderId: '487531490423',
    projectId: 'sadeem-c5307',
    storageBucket: 'sadeem-c5307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvUrUDhsPdxjNSrnWxPuR7xcHp729_GqM',
    appId: '1:487531490423:ios:e3639e661824623b39aa72',
    messagingSenderId: '487531490423',
    projectId: 'sadeem-c5307',
    storageBucket: 'sadeem-c5307.firebasestorage.app',
    iosBundleId: 'com.example.sadeemProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvUrUDhsPdxjNSrnWxPuR7xcHp729_GqM',
    appId: '1:487531490423:ios:e3639e661824623b39aa72',
    messagingSenderId: '487531490423',
    projectId: 'sadeem-c5307',
    storageBucket: 'sadeem-c5307.firebasestorage.app',
    iosBundleId: 'com.example.sadeemProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzCvHOWM6YCw08_Em9JjLL4YF_4zoph9g',
    appId: '1:487531490423:web:e7e6aecc1890991a39aa72',
    messagingSenderId: '487531490423',
    projectId: 'sadeem-c5307',
    authDomain: 'sadeem-c5307.firebaseapp.com',
    storageBucket: 'sadeem-c5307.firebasestorage.app',
    measurementId: 'G-QMZ5V6YP1P',
  );

}